[default]
DEBUG = true
SQLALCHEMY_DATABASE_URI = 'sqlite:///dev.db'
SQLALCHEMY_TRACK_MODIFICATIONS = false
TITLE = 'Consulta'
APP_NAME = 'Consulta'
EXTENSIONS = [
  "consulta.ext.database:init_app",
  "consulta.ext.commands:init_app",
  "consulta.blueprints:init_app"
]

[development]
EXTENSIONS = ["dynaconf_merge_unique"]
DEBUG = true